apiVersion: apps/v1
kind: Deployment
metadata:
  name: b8it148-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: v1-demo
  template:
    metadata:
      labels:
        deployment-name: v1-demo
    spec:
      containers:
      - name: b8it148-kubernetes-container
        image: 10536252/b8it148:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: b8it148-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    deployment-name: v1-demo
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002